# Generated by Django 3.1.4 on 2020-12-12 01:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desarrollador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desarrollador', models.CharField(max_length=100)),
                ('creacion', models.DateField(blank=True, null=True, verbose_name='Creación')),
            ],
            options={
                'ordering': ['desarrollador'],
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreJuego', models.CharField(help_text='Ingrese el nombre del genero del Juego (Ej. Acción - Aventura)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Idiomas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese los idiomas del juego (Ej. Español-Ingles-Japones-Chino Mandarin)', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('sinopsis', models.TextField(help_text='Ingresa una breve descripción del juego', max_length=1000)),
                ('clasificacion', models.TextField(help_text='Ingresa una clasificacion del juego', max_length=100)),
                ('foto', models.ImageField(upload_to='imagenes')),
                ('desarrollador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GGCatalogo.desarrollador')),
                ('genero', models.ManyToManyField(help_text='Seleccione un genero para este juego', to='GGCatalogo.Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID es único para cada juego en particular en toda la tienda', primary_key=True, serialize=False)),
                ('lanzamiento', models.CharField(max_length=20)),
                ('estado', models.CharField(blank=True, choices=[('a', 'agotado'), ('pv', 'Pre-venta'), ('d', 'Disponible')], default='m', help_text='Disponibilidad de Juego', max_length=2)),
                ('idioma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GGCatalogo.idiomas')),
                ('juegos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GGCatalogo.juego')),
            ],
        ),
    ]
